project:
  type: website

execute:
    freeze: auto

website:
  title: "Lucas van Walstijn"
  site-url: https://lucasvw.github.io
  favicon: profile.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lucasvw
      - icon: twitter
        href: https://twitter.com/lvWal
      - icon: linkedin
        href: https://www.linkedin.com/in/lucasvanwalstijn/
      - icon: rss
        href: https://lucasvw.github.io/index.xml
format:
  html:
    theme: [styles.scss, cosmo]
    css: styles.css
