project:
  type: website

execute:
    freeze: auto

website:
  title: "Lucas van Walstijn"
  favicon: profile.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/lucasvw
      - icon: twitter
        href: https://twitter.com/lvWal
      - icon: linkedin
        href: https://www.linkedin.com/in/lucasvanwalstijn/
format:
  html:
    theme: cosmo
    css: styles.css

