project:
  type: website

execute:
    freeze: auto

cookie-consent: true

website:
  title: "Lucas van Walstijn"
  google-analytics: "G-05FDFMB3LP"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

